# Generated by Django 6.0.8 on 2026-09-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='konu kodu')),
                ('name', models.CharField(max_length=200, verbose_name='konu adı')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme zamanı')),
            ],
            options={
                'verbose_name': 'konu',
                'verbose_name_plural': 'konular',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='topic_code_not_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='topic_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='MEB kazanım kodu')),
                ('description', models.TextField(verbose_name='kazanım açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme zamanı')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_outcomes', to='core.topic', verbose_name='konu')),
            ],
            options={
                'verbose_name': 'kazanım',
                'verbose_name_plural': 'kazanımlar',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='learning_outcome_code_not_empty'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='learning_outcome_description_not_empty')],
            },
        ),
    ]
