# Generated by Django 6.0.8 on 2026-09-19 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_question_code_counter(apps, schema_editor):
    question_code_counter = apps.get_model("core", "QuestionCodeCounter")
    question_code_counter.objects.create(pk=1, last_value=0)


def delete_question_code_counter(apps, schema_editor):
    question_code_counter = apps.get_model("core", "QuestionCodeCounter")
    question_code_counter.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'soru kodu sayacı',
                'verbose_name_plural': 'soru kodu sayaçları',
            },
        ),
        migrations.RunPython(
            create_question_code_counter,
            delete_question_code_counter,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=7, unique=True, verbose_name='soru kodu')),
                ('original_image', models.ImageField(upload_to='questions/originals/%Y/%m/', verbose_name='orijinal soru görseli')),
                ('question_text', models.TextField(verbose_name='LaTeX soru metni')),
                ('choice_a', models.TextField(verbose_name='LaTeX A şıkkı')),
                ('choice_b', models.TextField(verbose_name='LaTeX B şıkkı')),
                ('choice_c', models.TextField(verbose_name='LaTeX C şıkkı')),
                ('choice_d', models.TextField(verbose_name='LaTeX D şıkkı')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='doğru cevap')),
                ('source_pdf_name', models.CharField(max_length=255, verbose_name='kaynak PDF adı')),
                ('source_page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='kaynak sayfa numarası')),
                ('source_question_number', models.CharField(max_length=50, verbose_name='kaynak soru numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme zamanı')),
                ('learning_outcomes', models.ManyToManyField(related_name='questions', to='core.learningoutcome', verbose_name='kazanımlar')),
                ('primary_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_questions', to='core.topic', verbose_name='ana konu')),
                ('secondary_topics', models.ManyToManyField(blank=True, related_name='secondary_questions', to='core.topic', verbose_name='ikincil konular')),
            ],
            options={
                'verbose_name': 'soru',
                'verbose_name_plural': 'sorular',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='question_code_not_empty'), models.CheckConstraint(condition=models.Q(('question_text', ''), _negated=True), name='question_text_not_empty'), models.CheckConstraint(condition=models.Q(('choice_a', ''), _negated=True), name='question_choice_a_not_empty'), models.CheckConstraint(condition=models.Q(('choice_b', ''), _negated=True), name='question_choice_b_not_empty'), models.CheckConstraint(condition=models.Q(('choice_c', ''), _negated=True), name='question_choice_c_not_empty'), models.CheckConstraint(condition=models.Q(('choice_d', ''), _negated=True), name='question_choice_d_not_empty'), models.CheckConstraint(condition=models.Q(('correct_answer__in', ('A', 'B', 'C', 'D'))), name='question_correct_answer_valid'), models.CheckConstraint(condition=models.Q(('source_pdf_name', ''), _negated=True), name='question_source_pdf_name_not_empty'), models.CheckConstraint(condition=models.Q(('source_page_number__gte', 1)), name='question_source_page_number_positive'), models.CheckConstraint(condition=models.Q(('source_question_number', ''), _negated=True), name='question_source_question_number_not_empty')],
            },
        ),
    ]
