# Generated by Django 6.0.8 on 2026-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questioncodecounter_question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('original_image', ''), _negated=True), name='question_original_image_not_empty'),
        ),
    ]
