# Generated by Django 6.0.8 on 2026-09-20 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_question_type_code_counter(apps, schema_editor):
    question_type_code_counter = apps.get_model("core", "QuestionTypeCodeCounter")
    question_type_code_counter.objects.create(pk=1, last_value=0)


def delete_question_type_code_counter(apps, schema_editor):
    question_type_code_counter = apps.get_model("core", "QuestionTypeCodeCounter")
    question_type_code_counter.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_question_original_image_not_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'soru tipi kodu sayacı',
                'verbose_name_plural': 'soru tipi kodu sayaçları',
            },
        ),
        migrations.RunPython(
            create_question_type_code_counter,
            delete_question_type_code_counter,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='zorluk düzeyi'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, verbose_name='çözüm'),
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=6, unique=True, verbose_name='soru tipi kodu')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ad')),
                ('short_description', models.TextField(verbose_name='kısa açıklama')),
                ('solution_method', models.TextField(verbose_name='çözüm yöntemi veya işlem adımları')),
                ('classification_criteria', models.TextField(verbose_name='ayırt edici sınıflandırma ölçütleri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme zamanı')),
                ('example_questions', models.ManyToManyField(blank=True, related_name='example_for_question_types', to='core.question', verbose_name='örnek sorular')),
            ],
            options={
                'verbose_name': 'soru tipi',
                'verbose_name_plural': 'soru tipleri',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.questiontype', verbose_name='soru tipi'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__isnull', True), models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), _connector='OR'), name='question_difficulty_valid'),
        ),
        migrations.AddConstraint(
            model_name='questiontype',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='question_type_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='questiontype',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='question_type_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='questiontype',
            constraint=models.CheckConstraint(condition=models.Q(('short_description', ''), _negated=True), name='question_type_short_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='questiontype',
            constraint=models.CheckConstraint(condition=models.Q(('solution_method', ''), _negated=True), name='question_type_solution_method_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='questiontype',
            constraint=models.CheckConstraint(condition=models.Q(('classification_criteria', ''), _negated=True), name='question_type_classification_criteria_not_empty'),
        ),
    ]
