# Generated by Django 6.0.8 on 2026-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questiontypecodecounter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arşivlenme zamanı'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='görsel özeti'),
        ),
    ]
